import React from 'react'; import { createRoot } from 'react-dom/client'; import './style.css';
type Train={train_id:string;train_number:string;train_type:string;origin:string;destination:string;priority_class:number;status?:string;current_node?:string;delay_seconds?:number};
type Twin={simulation_time:number;trains:Record<string,Train>;active_conflicts:any[];predictions:any[];recommendations:any[]};
const API=import.meta.env.VITE_API_URL||'http://localhost:8000';
function App(){
 const [status,setStatus]=React.useState('idle'),[twin,setTwin]=React.useState<Twin|null>(null),[trains,setTrains]=React.useState<Train[]>([]),[error,setError]=React.useState(''),[busy,setBusy]=React.useState(false),[speed,setSpeed]=React.useState(1),[events,setEvents]=React.useState<string[]>([]);
 const load=React.useCallback(async()=>{try{setError('');const [s,t,live]=await Promise.all([fetch(`${API}/api/v1/system/status`),fetch(`${API}/api/v1/trains`),fetch(`${API}/api/v1/simulation/state`)]);if(!s.ok||!t.ok||!live.ok)throw Error('Backend request failed');setStatus((await s.json()).status);setTrains((await t.json()).items);setTwin((await live.json()).state)}catch(e){setError(e instanceof Error?e.message:'Unable to connect')}},[]);
 React.useEffect(()=>{load();const ws=new WebSocket(API.replace(/^http/,'ws')+'/ws/simulation');ws.onmessage=e=>{const data=JSON.parse(e.data);setEvents(v=>[(data.type||data.event_type||'event'),...v].slice(0,6));load()};return()=>ws.close()},[load]);
 async function command(action:string){setBusy(true);try{await fetch(`${API}/api/v1/simulation/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await load()}finally{setBusy(false)}}
 async function post(path:string,body:any={}){setBusy(true);try{await fetch(`${API}${path}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});await load()}finally{setBusy(false)}}
 const trainRows=twin?Object.values(twin.trains).slice(0,10):trains.slice(0,10);const conflicts=twin?.active_conflicts||[];const recommendation=twin?.recommendations?.[0];
 return <main><header><div><p className="eyebrow">RAIL-TWIN / CONTROL CENTRE</p><h1>Vasai Road digital twin</h1><p className="muted">Executable simulation · simulation time {twin?`${Math.round(twin.simulation_time/60)} min`:'—'}</p></div><div className="badge">SIMULATION DATA</div></header>
 {error&&<div className="alert">{error} — start the backend with Docker Compose.</div>}
 <section className="toolbar"><span className={`dot ${status==='running'?'live':''}`}></span><span>Simulation {status}</span><label className="scenario">Speed <select value={speed} onChange={e=>{setSpeed(Number(e.target.value));post('/api/v1/simulation/speed',{speed:Number(e.target.value)})}}><option value="1">1x</option><option value="5">5x</option><option value="10">10x</option><option value="20">20x</option></select></label><button disabled={busy} onClick={()=>command('start')}>Start</button><button disabled={busy} onClick={()=>command('pause')}>Pause</button><button disabled={busy} onClick={()=>command('resume')}>Resume</button><button disabled={busy} onClick={()=>command('reset')}>Reset</button><button disabled={busy} onClick={()=>post('/api/v1/simulation/event',{event_type:'freight.delay',target_type:'train',target_id:'T012',delay_seconds:480,reason:'Manual scenario trigger',severity:'HIGH'})}>Trigger +8m freight event</button></section>
 <section className="grid"><article className="card twin"><div className="cardhead"><h2>Digital twin</h2><span className="pill">7 platforms · junction</span></div><svg viewBox="0 0 900 300" role="img" aria-label="Vasai Road operational schematic"><path className="track" d="M30 42H870M30 82H870M30 122H870M30 162H870M30 202H870M30 242H870"/><path className="loop" d="M330 202H700V242H330"/><text x="35" y="30">Mumbai / Churchgate</text><text x="700" y="30">Virar / Dahanu</text><text x="350" y="192">Freight loop</text><text x="370" y="278">Vasai Road Junction</text><circle cx="450" cy="122" r="10" className="node"/></svg><p className="caption">Physical movement, block occupancy, event delay, and resource state are computed by the SimPy twin.</p></article>
 <article className="card"><div className="cardhead"><h2>Fleet state</h2><span className="pill">{trainRows.length} visible trains</span></div>{trainRows.length?<div className="table">{trainRows.map(t=><div className="row" key={t.train_id}><b>{t.train_number||t.train_id}</b><span>{t.status||t.train_type}</span><span>{t.current_node||`${t.origin} → ${t.destination}`}</span><span className="priority">+{Math.round(t.delay_seconds||0)}s</span></div>)}</div>:<div className="empty">Start a simulation to populate train state.</div>}</article></section>
 <section className="grid three"><Panel title="Predictions" value={twin?.predictions?.length?`${twin.predictions.length} train predictions`:'No model output'} action={()=>post('/api/v1/predictions/run')}/><Panel title="Conflicts" value={conflicts.length?`${conflicts.length} detected`:'No active conflicts'} action={()=>post('/api/v1/conflicts/detect')}/><Panel title="Recommendations" value={recommendation?recommendation.reason:'No recommendation generated'} action={()=>post('/api/v1/optimization/run')}/></section>
 {recommendation&&<section className="card recommendation"><div className="cardhead"><h2>Controller decision</h2><span className="pill">{recommendation.safety_status}</span></div><p>{recommendation.reason}</p><button onClick={()=>post(`/api/v1/recommendations/${recommendation.recommendation_id}/accept`,{reason:'Controller accepted computed recommendation'})}>Accept</button><button onClick={()=>post(`/api/v1/recommendations/${recommendation.recommendation_id}/reject`,{reason:'Controller rejected recommendation'})}>Reject</button></section>}
 <section className="card"><div className="cardhead"><h2>Event stream</h2><span className="pill">WebSocket</span></div>{events.length?<div className="events">{events.map((e,i)=><span key={i}>{e}</span>)}</div>:<div className="empty">Waiting for simulation events.</div>}</section></main>}
 function Panel({title,value,action}:{title:string;value:string;action:()=>void}){return <article className="card panel"><div className="cardhead"><h2>{title}</h2><span className="pill">LIVE</span></div><p className="muted">{value}</p><button onClick={action}>Run</button></article>}
 createRoot(document.getElementById('root')!).render(<App/>);
