import React from 'react'; import { createRoot } from 'react-dom/client'; import './style.css';
type Train = { train_id:string; train_number:string; train_type:string; origin:string; destination:string; priority_class:number };
type Status = { status:string; scenario_id:string; environment:string };
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
function App(){
 const [status,setStatus]=React.useState<Status|null>(null); const [trains,setTrains]=React.useState<Train[]>([]); const [error,setError]=React.useState(''); const [busy,setBusy]=React.useState(false); const [events,setEvents]=React.useState<string[]>([]);
 const load=React.useCallback(async()=>{try{setError(''); const [s,t]=await Promise.all([fetch(`${API}/api/v1/system/status`),fetch(`${API}/api/v1/trains`)]); if(!s.ok||!t.ok) throw new Error('Backend request failed'); setStatus(await s.json()); setTrains((await t.json()).items)}catch(e){setError(e instanceof Error?e.message:'Unable to connect')}} ,[]);
 React.useEffect(()=>{load(); const ws=new WebSocket(API.replace(/^http/,'ws')+'/ws/simulation'); ws.onmessage=e=>setEvents(v=>[JSON.parse(e.data).event_type||JSON.parse(e.data).type,...v].slice(0,5)); return()=>ws.close()},[load]);
 async function command(action:string){setBusy(true); try{await fetch(`${API}/api/v1/simulation/${action}`,{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'}); await load()}finally{setBusy(false)}}
 return <main><header><div><p className="eyebrow">RAIL-TWIN / CONTROL CENTRE</p><h1>Vasai Road digital twin</h1><p className="muted">Decision support for predictive train traffic management</p></div><div className="badge">SIMULATION DATA</div></header>
 {error&&<div className="alert">{error} — start the backend with Docker Compose.</div>}
 <section className="toolbar"><span className={`dot ${status?.status==='running'?'live':''}`}></span><span>{status?`Simulation ${status.status}`:'Loading system status…'}</span><span className="scenario">{status?.scenario_id||'vasai-disruption-v1'}</span><button disabled={busy} onClick={()=>command('start')}>Start</button><button disabled={busy} onClick={()=>command('pause')}>Pause</button><button disabled={busy} onClick={()=>command('reset')}>Reset</button></section>
 <section className="grid"><article className="card twin"><div className="cardhead"><h2>Digital twin</h2><span className="pill">7 platforms · junction</span></div><svg viewBox="0 0 900 300" role="img" aria-label="Vasai Road operational schematic"><path className="track" d="M30 42H870M30 82H870M30 122H870M30 162H870M30 202H870M30 242H870"/><path className="loop" d="M330 202H700V242H330"/><text x="35" y="30">Mumbai / Churchgate</text><text x="700" y="30">Virar / Dahanu</text><text x="350" y="192">Freight loop</text><text x="370" y="278">Vasai Road Junction</text><circle cx="450" cy="122" r="10" className="node"/></svg><p className="caption">Prototype topology derived from the approved Vasai Road platform grouping. Track-level detail is simulation data.</p></article>
 <article className="card"><div className="cardhead"><h2>Fleet state</h2><span className="pill">{trains.length} seeded trains</span></div>{trains.length?<div className="table">{trains.slice(0,8).map(t=><div className="row" key={t.train_id}><b>{t.train_number}</b><span>{t.train_type}</span><span>{t.origin} → {t.destination}</span><span className="priority">P{t.priority_class}</span></div>)}</div>:<div className="empty">No train state available.</div>}</article></section>
 <section className="grid three"><Panel title="Predictions" text="No prediction run has been executed."/><Panel title="Conflicts" text="No conflicts have been detected."/><Panel title="Recommendations" text="No recommendations have been generated."/></section>
 <section className="card"><div className="cardhead"><h2>Event stream</h2><span className="pill">WebSocket</span></div>{events.length?<div className="events">{events.map((e,i)=><span key={i}>{e}</span>)}</div>:<div className="empty">Waiting for simulation events.</div>}</section></main>}
 function Panel({title,text}:{title:string;text:string}){return <article className="card panel"><div className="cardhead"><h2>{title}</h2><span className="pill">EMPTY</span></div><p className="muted">{text}</p></article>}
 createRoot(document.getElementById('root')!).render(<App/>);
